---
- name: "JBoss EAP installation and configuration"
  hosts: jboss-servers
  become: yes
  vars:
    jboss_eap_user: jboss-eap
    jboss_eap_group: jboss-eap
    eap_deploy_dir: /opt
    eap_version: 7.4
    eap_link: https://www.dropbox.com/s/ukq5tbrfegkz313/jboss-eap-7.4.0.zip?dl=1
    eap_archive: jboss-eap-7.4.0.zip
    eap_home: "{{ eap_deploy_dir }}/jboss-eap-{{eap_version}}"
    eap_all: "{{ eap_deploy_dir }}/jboss-eap-*/"
    rhel_initd: /etc/init.d
    jboss_eap_service_conf_dir: "/etc/default"
  tasks:
      - name: Install JBoss Requirements
        ansible.builtin.dnf:
           name: unzip, initscripts, hostname
           state: present

      - name: Check if service exists
        stat: path=/etc/init.d/jboss-eap-rhel.sh
        register: service_status

      - name: Ensure EAP service is stopped
        when: service_status.stat.exists
        ignore_errors: true
        service:
           name: jboss-eap-rhel
           state: stopped

      - name: Create JBoss EAP Group
        group:
         name: "{{ jboss_eap_group }}"
         system: yes
         state: present
         gid: "{{ jboss_eap_group_gid | default('400') }}"

      - name: Create JBoss EAP User
        user:
          name: "{{ jboss_eap_user }}"
          comment: "JBoss EAP User"
          uid: "{{ jboss_eap_user_uid | default('400') }}"
          group: "{{ jboss_eap_group }}"
          home: "{{ eap_deploy_dir }}"

      - name: Clean EAP directory
        file:
           state: absent
           path: "{{ eap_home }}"

      - name: Remove EAP directories (for different versions)
        file:
          state: absent
          path: "{{ eap_all }}"
      - name: "Obtains JBoss repository"
        get_url:
           url: "{{ eap_link }}"
           dest: "{{ eap_deploy_dir }}"

      - name: Unarchive EAP
        unarchive:
           src:  "{{ eap_deploy_dir }}/{{ eap_archive }}"
           dest: "{{ eap_deploy_dir }}"
           owner: "{{ jboss_eap_user }}"
           group: "{{ jboss_eap_group }}"
           remote_src: yes

      - name: Clear JBoss Zip File
        file:
         state: absent
         path: "{{ eap_deploy_dir }}/{{ eap_archive }}"

      - name: Create symlink
        file:
           src: "{{eap_home}}"
           dest: "/opt/jboss-eap"
           state: link
           force: yes

      - name: Modify JBoss EAP Configuration File
        lineinfile:
          state: present
          path: "{{ eap_home }}/bin/init.d/jboss-eap.conf"
          regexp: "{{ item.regexp }}"
          line: "{{ item.line }}"
        with_items:
        - {regexp: "^# JBOSS_USER=", line: "JBOSS_USER=jboss-eap"}
        - {regexp: "^# JBOSS_CONFIG=", line: "JBOSS_CONFIG=standalone-ha.xml"}
        - {regexp: "^# JBOSS_OPTS=", line: "JBOSS_OPTS=\"-b 0.0.0.0 -bprivate `hostname -i` -Djboss.node.name={{ inventory_hostname }}\""}

      - name: Copy JBoss Service Configuration File
        copy:
          src: "{{ eap_home }}/bin/init.d/jboss-eap.conf"
          dest: "{{ jboss_eap_service_conf_dir }}/"
          remote_src: True
          owner: "{{ jboss_eap_user }}"
          group: "{{ jboss_eap_group }}"

      - name: Start EAP servers
        shell: "nohup sh {{ eap_home }}/bin/standalone.sh  -c standalone-full.xml -b 0.0.0.0 -Djboss.as.management.blocking.timeout=5000 2>&1 &"

     # - name: Create Admin Users juhan on each application
     #   shell: "sh {{ eap_home }}/bin/add-user.sh juhan passw0rd"
