---
- name: "JBoss EAP installation and configuration"
  hosts: appservers
  become: yes
  #become_user: ansible
  vars:
    jboss_eap_user: jboss-eap
    jboss_eap_group: jboss-eap
    eap_deploy_dir: /opt
    eap_version:  7.4
    jboss_home: "{{ eap_deploy_dir }}/jboss-eap-{{eap_version}}"
    eap_all: "{{ eap_deploy_dir }}/jboss-eap-*/"
    deployment_file: /tmp/__browsestore.war
    app_name: '__browsestore.war'
  tasks:
  - name: Ensures webapp War file has been retrieved from the url
    copy:
       src: "{{ deployment_file }}"
       dest: "{{ eap_deploy_dir }}"
       remote_src: yes
       owner: "{{ jboss_eap_user }}"
       group: "{{ jboss_eap_group }}"

  - name: Copy application to JBoss deployments directory
    copy:
     src: "{{ eap_deploy_dir }}/{{ app_name }}"
     dest: "{{ jboss_home }}/standalone/deployments/{{ app_name }}"
     remote_src: True

  - name: Print deployment status
    debug:
      msg: "Application {{ app_name }} deployed successfully."
